class_name SystemDB
extends RefCounted
# The STAR CATALOGUE you travel. Each system is its own star-centred frame in km
# (1 scene unit = 1 km, Newton, anchored positions — docs/adr/0002): Sol from JPL/NASA
# (SolEphemeris), every other star generated at real scale from its row + seed
# (GeneratedEphemeris). You never fly the real interstellar distance; the light-year
# distance + sky coordinates are display/transit/map metadata only.
#
# Two data sources, unified by id (see _rows):
#   • STARS    — ~45 REAL nearest stars (generated by tools/gen_star_catalog.py from the
#                J2000 nearest-star table). Each cooks from spectral type.
#   • AUTHORED — rows with hand-set metadata (Sol, Proxima, TRAPPIST-1, K2-18, the imaginary
#                Alien zone); their worlds are generated like every other star's.
#
# A "body spec" is what PlanetSystem.load_system() consumes (see sol_from): name,
# radius (km), color, glow, model (opt GLB/OBJ), star (bool), parent (moons).
# Positions always come from the system's ephemeris.

const SOL := "sol"
const K2_18 := "k2-18"
const PROXIMA := "proxima"
const TRAPPIST := "trappist"
const ALIEN := "alien"           # the hostile combat zone (Vortex + aliens)

# Catalog stars cook from spectral type. sol.obj is no longer the default sun.

# --- generated by tools/gen_star_catalog.py — real nearest stars (J2000) ---
# Accuracy: hand-transcribed RA/Dec/distance, good to display precision (not science-grade);
# rerun the generator / edit rows to refine. Colour follows spectral class (O/B blue→M red).
static var STARS := [
	{ "id": "alpha_centauri", "name": "Alpha Centauri", "ly": 4.34, "ra": 219.902, "dec": -60.834, "spectral": "G2V", "color": Color(1.00, 0.92, 0.65) },
	{ "id": "barnards_star", "name": "Barnard's Star", "ly": 5.96, "ra": 269.452, "dec": 4.693, "spectral": "M4.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "luhman_16", "name": "Luhman 16", "ly": 6.51, "ra": 162.329, "dec": -53.319, "spectral": "L8", "color": Color(0.72, 0.34, 0.26) },
	{ "id": "wolf_359", "name": "Wolf 359", "ly": 7.86, "ra": 164.122, "dec": 7.015, "spectral": "M6.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "lalande_21185", "name": "Lalande 21185", "ly": 8.30, "ra": 165.834, "dec": 35.970, "spectral": "M2.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "sirius", "name": "Sirius", "ly": 8.71, "ra": 101.287, "dec": -16.716, "spectral": "A1V", "color": Color(0.95, 0.96, 1.00) },
	{ "id": "luyten_726-8", "name": "Luyten 726-8", "ly": 8.77, "ra": 24.755, "dec": -17.950, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ross_154", "name": "Ross 154", "ly": 9.71, "ra": 282.456, "dec": -23.836, "spectral": "M3.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ross_248", "name": "Ross 248", "ly": 10.31, "ra": 355.478, "dec": 44.175, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "epsilon_eridani", "name": "Epsilon Eridani", "ly": 10.47, "ra": 53.232, "dec": -9.458, "spectral": "K2V", "color": Color(1.00, 0.76, 0.42) },
	{ "id": "lacaille_9352", "name": "Lacaille 9352", "ly": 10.72, "ra": 346.467, "dec": -35.853, "spectral": "M0.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ross_128", "name": "Ross 128", "ly": 11.01, "ra": 176.935, "dec": 0.804, "spectral": "M4.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ez_aquarii", "name": "EZ Aquarii", "ly": 11.11, "ra": 339.639, "dec": -15.299, "spectral": "M5.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "61_cygni", "name": "61 Cygni", "ly": 11.40, "ra": 316.725, "dec": 38.749, "spectral": "K5.0V", "color": Color(1.00, 0.76, 0.42) },
	{ "id": "procyon", "name": "Procyon", "ly": 11.46, "ra": 114.825, "dec": 5.225, "spectral": "F5IV", "color": Color(1.00, 0.98, 0.92) },
	{ "id": "struve_2398", "name": "Struve 2398", "ly": 11.49, "ra": 280.695, "dec": 59.630, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "groombridge_34", "name": "Groombridge 34", "ly": 11.62, "ra": 4.595, "dec": 44.023, "spectral": "M1.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "dx_cancri", "name": "DX Cancri", "ly": 11.68, "ra": 127.456, "dec": 26.777, "spectral": "M6.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "epsilon_indi", "name": "Epsilon Indi", "ly": 11.87, "ra": 330.840, "dec": -56.786, "spectral": "K5V", "color": Color(1.00, 0.76, 0.42) },
	{ "id": "tau_ceti", "name": "Tau Ceti", "ly": 11.91, "ra": 26.017, "dec": -15.938, "spectral": "G8.5V", "color": Color(1.00, 0.92, 0.65) },
	{ "id": "gj_1061", "name": "GJ 1061", "ly": 11.98, "ra": 53.999, "dec": -44.513, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "yz_ceti", "name": "YZ Ceti", "ly": 12.12, "ra": 18.127, "dec": -16.999, "spectral": "M4.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "luytens_star", "name": "Luyten's Star", "ly": 12.35, "ra": 111.852, "dec": 5.226, "spectral": "M3.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "teegardens_star", "name": "Teegarden's Star", "ly": 12.50, "ra": 43.254, "dec": 16.881, "spectral": "M6.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "kapteyns_star", "name": "Kapteyn's Star", "ly": 12.83, "ra": 77.919, "dec": -45.018, "spectral": "M1.5VI", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "lacaille_8760", "name": "Lacaille 8760", "ly": 12.95, "ra": 319.314, "dec": -38.867, "spectral": "M0.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "scr_1845", "name": "SCR 1845-6357", "ly": 13.06, "ra": 281.272, "dec": -63.963, "spectral": "M8.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "kruger_60", "name": "Kruger 60", "ly": 13.07, "ra": 336.998, "dec": 57.696, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "denis_1048", "name": "DENIS J1048-3956", "ly": 13.19, "ra": 162.061, "dec": -39.935, "spectral": "M8.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ross_614", "name": "Ross 614", "ly": 13.36, "ra": 97.347, "dec": -2.814, "spectral": "M4.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "wolf_1061", "name": "Wolf 1061", "ly": 14.05, "ra": 247.575, "dec": -12.662, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "van_maanens_star", "name": "Van Maanen's Star", "ly": 14.07, "ra": 12.291, "dec": 5.389, "spectral": "DZ7", "color": Color(0.86, 0.90, 1.00) },
	{ "id": "gliese_1", "name": "Gliese 1", "ly": 14.17, "ra": 1.352, "dec": -37.358, "spectral": "M1.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "tz_arietis", "name": "TZ Arietis", "ly": 14.58, "ra": 30.055, "dec": 13.052, "spectral": "M4.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "wolf_424", "name": "Wolf 424", "ly": 14.60, "ra": 188.322, "dec": 9.021, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_687", "name": "Gliese 687", "ly": 14.84, "ra": 264.108, "dec": 68.339, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_674", "name": "Gliese 674", "ly": 14.85, "ra": 262.166, "dec": -46.895, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "lhs_292", "name": "LHS 292", "ly": 14.87, "ra": 162.053, "dec": -11.337, "spectral": "M6.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_440", "name": "Gliese 440", "ly": 15.12, "ra": 176.429, "dec": -64.841, "spectral": "DQ6", "color": Color(0.86, 0.90, 1.00) },
	{ "id": "gj_1245", "name": "GJ 1245", "ly": 15.20, "ra": 298.476, "dec": 44.415, "spectral": "M5.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_876", "name": "Gliese 876", "ly": 15.24, "ra": 343.320, "dec": -14.264, "spectral": "M3.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "groombridge_1618", "name": "Groombridge 1618", "ly": 15.89, "ra": 152.842, "dec": 49.454, "spectral": "K7.0V", "color": Color(1.00, 0.76, 0.42) },
	{ "id": "gliese_412", "name": "Gliese 412", "ly": 16.00, "ra": 166.369, "dec": 43.527, "spectral": "M1.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "ad_leonis", "name": "AD Leonis", "ly": 16.19, "ra": 154.902, "dec": 19.869, "spectral": "M3.0V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "gliese_832", "name": "Gliese 832", "ly": 16.20, "ra": 323.392, "dec": -49.009, "spectral": "M1.5V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": "omicron2_eridani", "name": "Omicron-2 Eridani", "ly": 16.33, "ra": 63.818, "dec": -7.653, "spectral": "K0.5V", "color": Color(1.00, 0.76, 0.42) },
]

# Authored metadata; non-Sol worlds use the shared seeded generator.
# `map` overrides the 2D chart position for the imaginary Alien zone.
static var AUTHORED := [
	{ "id": SOL, "name": "Sol", "ly": 0.0, "ra": 0.0, "dec": 0.0, "spectral": "G2V", "color": Color(1.00, 0.85, 0.30) },
	{ "id": PROXIMA, "name": "Proxima b", "star_name": "Proxima Centauri", "planet_prefix": "Proxima", "ly": 4.24, "ra": 217.429, "dec": -62.679, "spectral": "M5.5V", "color": Color(1.00, 0.40, 0.24) },
	{ "id": TRAPPIST, "name": "TRAPPIST-1", "ly": 39.0, "ra": 346.622, "dec": -5.041, "spectral": "M8V", "color": Color(1.00, 0.50, 0.30) },
	{ "id": K2_18, "name": "K2-18", "ly": 124.0, "ra": 172.560, "dec": 7.588, "spectral": "M2.5V", "color": Color(1.00, 0.45, 0.28) },
	# Arcturus: Ramirez & Allende Prieto 2011, https://arxiv.org/abs/1109.4425.
	{ "id": "arcturus", "name": "Arcturus", "ly": 36.7, "ra": 213.915, "dec": 19.182, "spectral": "K1.5III", "stellar": {"type": "giant", "temperature_k": 4286.0, "radius_solar": 25.4, "mass_solar": 1.08} },
	# Aldebaran: A&A 553 A3 (2013); rounded mass is a modeling estimate (docs/STAR_RECIPES.md).
	{ "id": "aldebaran", "name": "Aldebaran", "ly": 66.6, "ra": 68.980, "dec": 16.509, "spectral": "K5III", "stellar": {"type": "giant", "temperature_k": 3900.0, "radius_solar": 44.0, "mass_solar": 1.2} },
	# Chandra Vela (2013) / Crab (2008), NASA SVS 13737; core physics uses family estimates.
	{ "id": "vela_pulsar", "name": "Vela Pulsar", "ly": 1000.0, "ra": 128.836, "dec": -45.176, "spectral": "REMNANT", "stellar_type": "pulsar" },
	{ "id": "crab_pulsar", "name": "Crab Pulsar", "ly": 6500.0, "ra": 83.633, "dec": 22.014, "spectral": "REMNANT", "stellar_type": "pulsar" },
	{ "id": ALIEN, "name": "Alien Zone", "star_name": "Hostile Star", "ly": 666.0, "ra": 0.0, "dec": 0.0, "spectral": "—", "color": Color(0.95, 0.15, 0.12), "hostile": true, "map": Vector2(-30.0, -26.0) },
]

static var _by_id := {}   # id -> row (lazy union of AUTHORED + STARS, authored first)

# --- catalogue lookup -------------------------------------------------------
static func _rows() -> Dictionary:
	if _by_id.is_empty():
		for r in AUTHORED:
			_by_id[r.id] = r
		for r in STARS:
			_by_id[r.id] = r
	return _by_id

static func _row(id: String) -> Dictionary:
	return _rows().get(id, {})

# Every travel destination (authored + real stars).
static func all() -> Array:
	return _rows().keys()

static func display_name(id: String) -> String:
	var r := _row(id)
	return str(r.get("name", id)) if not r.is_empty() else id

# Reverse of display_name, for the name-keyed sky shell. "" if the name isn't a destination.
static func id_for_name(nm: String) -> String:
	# The destination is named after its planet; the stellar body/sky marker is not.
	if nm == "Proxima Centauri":
		return PROXIMA
	for id in _rows():
		if str(_rows()[id].get("name", "")) == nm:
			return id
	return ""

static func star_row(id: String) -> Dictionary:
	return _row(id)


static func light_years(id: String) -> float:
	return float(_row(id).get("ly", 0.0))

static func spectral(id: String) -> String:
	return str(_row(id).get("spectral", ""))

static func family_label(id: String) -> String:
	var stellar: Dictionary = StarRecipe.resolve(_row(id)).stellar
	var family := str(stellar.type)
	if family == "giant" and float(stellar.temperature_k) <= 5000.0:
		return "Red Giant"
	if family in ["pulsar", "magnetar"]:
		return "Neutron Star · " + family.capitalize()
	return family.capitalize()

static func star_color(id: String) -> Color:
	return StarRecipe.resolve(_row(id)).color_a

# Hostile systems spawn the always-on alien swarm + Vortex boss. (Per-star GUARDIANS that
# gate discovery are separate — see main._is_guarded.)
static func is_hostile(id: String) -> bool:
	return bool(_row(id).get("hostile", false))


# Real 3D position from Sol in light-years (RA/Dec/distance → cartesian). Used for the
# star-map layout and for distance-scaled transit between any two systems.
static func coord(id: String) -> Vector3:
	var r := _row(id)
	var ra := deg_to_rad(float(r.get("ra", 0.0)))
	var dec := deg_to_rad(float(r.get("dec", 0.0)))
	var d := float(r.get("ly", 0.0))
	return Vector3(d * cos(dec) * cos(ra), d * sin(dec), d * cos(dec) * sin(ra))

# 2D chart position for the star map (equatorial-plane projection of coord). The Alien
# zone uses a hand-set `map` override since it isn't a real sky position.
static func galaxy_pos(id: String) -> Vector2:
	var r := _row(id)
	if r.has("map"):
		return r.map
	var c := coord(id)
	return Vector2(c.x, c.z)


# Teleport platforms: Sol always (the home station), any other system once visited.
# Until the interstellar drive exists that is the only way to reach another star.
static func is_teleport_platform(star: String) -> bool:
	return star == SOL or GameState.visited.has(star)

static func has_station(star: String) -> bool:
	return is_teleport_platform(star)


# Short arrival lore (shown once, the first time you reach a system). Empty = no card.
static func lore(id: String) -> String:
	return {
		PROXIMA: "The nearest other sun — a dim red coal 4.24 light-years out, and the\nfirst light most pilots ever claim that isn't our own. Proxima b huddles\nclose to its fire, scorched on one face and frozen on the other.",
		TRAPPIST: "An ultra-cool dwarf with seven worlds packed tight around it, close\nenough that from one you'd see the others as moons. The Survey sends\nits steady hands here — a lot of beacons to plant, all within reach.",
		K2_18: "124 light-years out: a sub-Neptune in its star's temperate lane, the\nkind of world the old telescopes argued over for decades. A long haul\nfor one line in the Atlas — but it's a line few names are on.",
		ALIEN: "Past the charted suns. The hostiles drift here, and among them Vortex —\nan alien hull grown monstrous, lit with a red menace the dark can't\nswallow. The deep catalog lies on the far side of him. Fly armed.",
	}.get(id, "")

static func bodies(id: String) -> Array:
	return sol_from(Ephemeris.system_for(id).live_worlds())


# Spawn specs for the Sol cook. Keeps parent so moons stay moons.
static func sol_from(worlds: Array) -> Array:
	var out := []
	# Every world of the system; Voyagers stay out this pass.
	for p in worlds:
		if p.get("craft", false):
			continue
		var b := {
			"name": p.name, "radius": p.radius, "color": p.color,
			"glow": p.get("glow", 1.0), "star": p.get("star", false),
			"mass": p.get("mass", 1.0),
			"ring": p.get("ring", false),
			"craft": p.get("craft", false),
			"drift": p.get("drift", 0.0),
			"physical": p.get("physical", false),
		}
		if p.has("model"):
			b["model"] = p.model
		if p.has("parent"):
			b["parent"] = p.parent
		for k in ["kind", "air_amount", "spectral", "stellar_type", "stellar"]:
			if p.has(k):
				b[k] = p[k].duplicate(true) if p[k] is Dictionary or p[k] is Array else p[k]
		out.append(b)
	return out
