#!/usr/bin/env python3
"""Build a Godot-safe Dingo57 OBJ without changing any geometry.

The supplied OBJ has 352 groups and 678 material switches, which exceeds Godot's
256-surface ArrayMesh limit and truncates the hull. SketchUp also splits those
groups across opaque and Translucent_Glass materials, so a viewer can see
through panels that are solid in the source model. This builder keeps the eight
user-identified booster groups as dedicated surfaces and merges every remaining
face into one opaque hull_body surface. Vertex/UV/normal/face records are copied
exactly; only face order and surface metadata change.
"""

from __future__ import annotations

import argparse
import zipfile
from collections import OrderedDict
from pathlib import Path


BOOSTER_GROUPS = {"Group_113", "Group_111", "Group_115", "Group_070",
                  "Group_109", "Group_072", "Group_076", "Group_074"}


def build(source: Path, output: Path, material_output: Path) -> tuple[int, int, int]:
    attributes: list[str] = []
    buckets: OrderedDict[str, list[str]] = OrderedDict()
    current_group = ""
    triangle_count = 0

    if source.suffix.lower() == ".zip":
        with zipfile.ZipFile(source) as archive:
            obj_names = [name for name in archive.namelist() if name.lower().endswith(".obj")]
            if len(obj_names) != 1:
                raise ValueError("expected exactly one OBJ in %s" % source)
            source_lines = archive.read(obj_names[0]).decode("utf-8-sig").splitlines()
    else:
        source_lines = source.read_text(encoding="utf-8-sig").splitlines()
    for raw in source_lines:
        line = raw.rstrip()
        fields = line.split()
        if not fields:
            continue
        token = fields[0]
        if token in {"v", "vt", "vn", "vp"}:
            attributes.append(line)
        elif token == "g" and len(fields) > 1:
            current_group = fields[1]
        elif token == "f":
            if current_group in BOOSTER_GROUPS:
                key = "booster_group_%s" % current_group.removeprefix("Group_")
            else:
                # Keep the whole remaining hull as one opaque surface. Per-material
                # buckets previously parked chassis faces in Translucent_Glass
                # surfaces, and one-sided winding then hid those panels in game.
                key = "hull_body"
            buckets.setdefault(key, []).append(line)
            triangle_count += len(fields) - 3

    with output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("# Godot-safe derived mesh; generated by tools/build_dingo57_obj.py\n")
        stream.write("# Geometry records are copied from the supplied Dingo57 OBJ; hull materials stay default.\n")
        stream.write("mtllib %s\n\n" % material_output.name)
        stream.write("\n".join(attributes))
        stream.write("\n")
        for key, faces in buckets.items():
            stream.write("\no %s\nusemtl %s\ns 1\n" % (key, key))
            stream.write("\n".join(faces))
            stream.write("\n")

    with material_output.open("w", encoding="utf-8", newline="\n") as stream:
        stream.write("# Opaque hull plus booster materials. The downloaded archive omitted\n")
        stream.write("# its referenced 3d-model.mtl; hull_body is forced fully opaque (d 1).\n\n")
        material_blocks = [
            "newmtl hull_body\nKd 0.30 0.31 0.34\nKs 0.40 0.40 0.40\nNs 64\nd 1",
        ]
        for group in sorted(BOOSTER_GROUPS):
            name = "booster_group_%s" % group.removeprefix("Group_")
            material_blocks.append("newmtl %s\nKd 1 1 1\nKs 1 1 1\nNs 128\nd 1" % name)
        stream.write("\n\n".join(material_blocks) + "\n")

    return len(buckets), triangle_count, len(attributes)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("material_output", type=Path)
    args = parser.parse_args()
    surface_count, triangles, attributes = build(args.source, args.output, args.material_output)
    print("surfaces=%d triangles=%d expected_indices=%d attributes=%d" %
          (surface_count, triangles, triangles * 3, attributes))


if __name__ == "__main__":
    main()
